# Generated by Django 3.2.13 on 2023-09-22 06:36

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('scho_meta', models.CharField(blank=True, max_length=1000, null=True)),
                ('opp_desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email_address', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.CharField(blank=True, max_length=500, null=True)),
                ('deadline', models.CharField(blank=True, max_length=500, null=True)),
                ('opp_type', multiselectfield.db.fields.MultiSelectField(choices=[('Announcement', 'Announcement'), ('Award/Grant', 'Award/Grant'), ('Competition', 'Competition'), ('Conference', 'Conference'), ('Courses', 'Courses'), ('Event', 'Event'), ('Fellowship', 'Fellowship'), ('Job', 'Job'), ('Leadership Program', 'Leadership Program'), ('Mentorship', 'Mentorship'), ('Online Courses', 'Online Courses'), ('Research', 'Research'), ('Residency Program', 'Residency Program'), ('Scholarship', 'Scholarship'), ('Short Program', 'Short Program'), ('Training', 'Training'), ('Volunteer Program', 'Volunteer Program'), ('Volunteer Compaign', 'Volunteer Compaign'), ('Volunteer Job', 'Volunteer Job')], max_length=234, null=True)),
                ('opp_apply_type', models.CharField(blank=True, max_length=500, null=True)),
                ('lang_requirements', multiselectfield.db.fields.MultiSelectField(choices=[('toefl', 'TOEFL'), ('ielts', 'IELTS'), ('delf/dalf(french)', 'DELF/DALF(French)'), ('hsk(chines)', 'HSK(CHINES)'), ('pte_academic', 'PTE Academic'), ('cambridge qualification', 'Cambridge qualification'), ('dsh_german', 'DSH German'), ('cefr', 'CEFR'), ('duolingo', 'Duolingo'), ('japan_language(jlpt)', 'Japan Language(JLPT)'), ('tomor(turkish)', 'TOMOR(Turkish)'), ('other', 'Other'), ('not_required', 'Not required')], max_length=158, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('male/female', 'Male/Female')], default='Male/Female', max_length=50, null=True)),
                ('level', multiselectfield.db.fields.MultiSelectField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PH.D'), ('school', 'School'), ('research', 'Research'), ('postdoc', 'PostDoc'), ('non_degree/short_program', 'Non-Degree /Short Program')], max_length=68, null=True)),
                ('number_of_opp', models.CharField(blank=True, max_length=50, null=True)),
                ('eligible_countries', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('medium_of_instruction', multiselectfield.db.fields.MultiSelectField(choices=[('english', 'English'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('turkish', 'Turkish'), ('slovaki', 'Slovaki'), ('romani', 'Romani'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('arabic', 'Arabic'), ('persian', 'Persian'), ('russian', 'Russian')], max_length=99, null=True)),
                ('field_of_stady', models.CharField(blank=True, max_length=500, null=True)),
                ('funding_type', multiselectfield.db.fields.MultiSelectField(choices=[('fully_funded', 'Fully Funded'), ('partially_founded', 'Partially Founded'), ('self_founded', 'Self Founded')], max_length=43, null=True)),
                ('duration', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('full_address', models.CharField(blank=True, max_length=500, null=True)),
                ('scho_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 22, 6, 36, 19, 204349, tzinfo=utc))),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('opp_slug', models.SlugField(blank=True, max_length=1000)),
                ('country_slug', models.SlugField(blank=True, max_length=1000)),
                ('organization_slug', models.SlugField(blank=True, max_length=1000)),
                ('views', models.IntegerField(default=0)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
