# Generated by Django 3.2.13 on 2023-09-22 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='scho_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 22, 10, 9, 9, 339446, tzinfo=utc)),
        ),
    ]
