# Generated by Django 3.2.13 on 2024-02-22 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_alter_detail_scho_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='scho_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 22, 6, 18, 33, 97047, tzinfo=utc)),
        ),
    ]
