# Generated by Django 3.2.13 on 2023-09-22 06:36

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_slug', models.SlugField(max_length=1000)),
                ('job_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('meta_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_location', models.CharField(blank=True, max_length=500, null=True)),
                ('nationality', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug_cate', models.SlugField(blank=True, max_length=1000, null=True)),
                ('slug_cpn', models.SlugField(allow_unicode=True, blank=True, max_length=1000, null=True)),
                ('emp_type', models.CharField(blank=True, max_length=300, null=True)),
                ('salary', models.CharField(blank=True, max_length=500, null=True)),
                ('vacancy_number', models.CharField(blank=True, max_length=500, null=True)),
                ('no_of_jobs', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('organzation', models.CharField(blank=True, max_length=1000, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=500, null=True)),
                ('contract_duration', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=500, null=True)),
                ('close_date', models.CharField(blank=True, max_length=500, null=True)),
                ('About_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('job_descriptions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('job_requirements', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('submission_guidelines', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('submission_email', models.CharField(blank=True, max_length=500, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('job_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 22, 6, 36, 19, 204349, tzinfo=utc))),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('views', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='approved', max_length=500, null=True)),
                ('org_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_photo.info')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
