# Generated by Django 3.2.13 on 2024-02-13 07:35

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('org_photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_auto_20240213_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='grade',
        ),
        migrations.AddField(
            model_name='info',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='org_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_photo.info'),
        ),
        migrations.AddField(
            model_name='info',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='approved', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='About_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='job_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 7, 35, 52, 79204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='info',
            name='job_descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='job_requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='submission_guidelines',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
