# Generated by Django 3.2.13 on 2024-02-18 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20240218_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='city_slug',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='info',
            name='company_type_slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='emp_type_slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='job_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 18, 7, 22, 0, 892895, tzinfo=utc)),
        ),
    ]
