# Generated by Django 3.2.13 on 2024-02-22 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20240218_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='work_from_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='job_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 22, 6, 18, 33, 97047, tzinfo=utc)),
        ),
    ]
