# Generated by Django 3.2.13 on 2023-09-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('vector_photo', models.ImageField(blank=True, null=True, upload_to='vector_photos/')),
            ],
        ),
    ]
