# Generated by Django 3.2.13 on 2023-07-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
