# Generated by Django 3.2.13 on 2023-07-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_userprofile_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_type',
            field=models.CharField(blank=True, choices=[('employer_private_sector', 'Employer (Private Sector)'), ('employer_public_sector', 'Employer (Public Sector)'), ('non_proft_organization', 'Non-Profit Organization'), ('recruitment_agency', 'Recruitment Agency')], max_length=500),
        ),
    ]
