# Generated by Django 3.2.13 on 2023-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0006_alter_userprofile_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_company',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_image',
            field=models.ImageField(null=True, upload_to='RegisteredCompaniesImages/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
