# Generated by Django 3.2.13 on 2023-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0007_auto_20230713_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='RegisteredCompaniesImages/'),
        ),
    ]
