# Generated by Django 3.2.13 on 2023-07-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
