# Generated by Django 3.2.13 on 2023-07-18 06:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0010_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_company',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
