# Generated by Django 3.2.13 on 2023-07-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0012_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
