# Generated by Django 3.2.13 on 2023-07-18 09:36

import Employer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0013_remove_userprofile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', Employer.models.UserManager()),
            ],
        ),
    ]
