# Generated by Django 3.2.13 on 2023-07-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0015_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verfied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
