# Generated by Django 3.2.13 on 2023-07-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0016_auto_20230726_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verfied',
        ),
    ]
